# Generated by Django 5.2.7 on 2025-10-22 14:00

import django.db.models.deletion
import hsk4.models.listening
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hsk4_listening_tasks',
            },
        ),
        migrations.CreateModel(
            name='FirstTaskHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('listening_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_tasks', to='hsk4.listeninghsk4')),
            ],
            options={
                'db_table': 'hsk4_listening_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='SecondTaskHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_letter', models.CharField(max_length=1, validators=[hsk4.models.listening.validate_uppercase_letter])),
                ('listening_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_type_tasks', to='hsk4.listeninghsk4')),
            ],
            options={
                'db_table': 'hsk4_listening_second_tasks',
            },
        ),
        migrations.CreateModel(
            name='SecondTaskHSK4Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, validators=[hsk4.models.listening.validate_uppercase_letter])),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk4.secondtaskhsk4')),
            ],
            options={
                'db_table': 'hsk4_listening_second_task_options',
            },
        ),
        migrations.CreateModel(
            name='ThirdTaskHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_letter', models.CharField(max_length=1, validators=[hsk4.models.listening.validate_uppercase_letter])),
                ('listening_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_type_tasks', to='hsk4.listeninghsk4')),
            ],
            options={
                'db_table': 'hsk4_listening_third_tasks',
            },
        ),
        migrations.CreateModel(
            name='ThirdTaskHSK4Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, validators=[hsk4.models.listening.validate_uppercase_letter])),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk4.thirdtaskhsk4')),
            ],
            options={
                'db_table': 'hsk4_listening_third_task_options',
            },
        ),
    ]
