# Generated by Django 5.2.7 on 2025-10-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsk4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingFirstTaskHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hsk4_reading_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hsk4_reading_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingFirstTaskOptionHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk4.readingfirsttaskhsk4')),
            ],
            options={
                'db_table': 'hsk4_reading_first_task_options',
            },
        ),
        migrations.CreateModel(
            name='ReadingFirstTaskSentenceHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='hsk4.readingfirsttaskhsk4')),
            ],
            options={
                'db_table': 'hsk4_reading_first_task_sentences',
            },
        ),
        migrations.AddField(
            model_name='readingfirsttaskhsk4',
            name='reading_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_tasks', to='hsk4.readinghsk4'),
        ),
        migrations.CreateModel(
            name='ReadingSecondTaskHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_sequence', models.CharField(max_length=5)),
                ('reading_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_type_tasks', to='hsk4.readinghsk4')),
            ],
            options={
                'db_table': 'hsk4_reading_second_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingSecondTaskOptionHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk4.readingsecondtaskhsk4')),
            ],
            options={
                'db_table': 'hsk4_reading_second_task_options',
            },
        ),
        migrations.CreateModel(
            name='ReadingThirdTaskHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('reading_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_type_tasks', to='hsk4.readinghsk4')),
            ],
            options={
                'db_table': 'hsk4_reading_third_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingThirdTaskQuestionHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk4.readingthirdtaskhsk4')),
            ],
            options={
                'db_table': 'hsk4_reading_third_task_questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionOptionHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk4.readingthirdtaskquestionhsk4')),
            ],
            options={
                'db_table': 'hsk4_reading_third_task_question_options',
            },
        ),
    ]
