# Generated by Django 5.2.7 on 2025-10-22 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsk4', '0002_readingfirsttaskhsk4_readinghsk4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hsk4_writing_tasks',
            },
        ),
        migrations.CreateModel(
            name='WritingFirstTaskHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_sentence', models.TextField()),
                ('words', models.TextField()),
                ('writing_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_tasks', to='hsk4.writinghsk4')),
            ],
            options={
                'db_table': 'hsk4_writing_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='WritingSecondTaskHSK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=255)),
                ('writing_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_type_tasks', to='hsk4.writinghsk4')),
            ],
            options={
                'db_table': 'hsk4_writing_second_tasks',
            },
        ),
        migrations.CreateModel(
            name='WritingSecondTaskWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('possible_answer', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='hsk4.writingsecondtaskhsk4')),
            ],
            options={
                'db_table': 'hsk4_writing_second_task_words',
            },
        ),
    ]
