# Generated by Django 5.2.7 on 2025-10-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTaskHSK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hsk1_listening_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='FourthTaskHSK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hsk1_listening_fourth_tasks',
            },
        ),
        migrations.CreateModel(
            name='ListeningHSK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hsk1_listening_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingFirstTaskHSK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hsk1_reading_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingFourthTaskHSK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hsk1_reading_fourth_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingHSK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hsk1_reading_tasks',
            },
        ),
        migrations.CreateModel(
            name='FirstTaskHSK1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk1.firsttaskhsk1')),
            ],
            options={
                'db_table': 'hsk1_listening_first_tasks_questions',
            },
        ),
        migrations.CreateModel(
            name='FourthTaskHSK1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk1.fourthtaskhsk1')),
            ],
            options={
                'db_table': 'hsk1_listening_fourth_tasks_questions',
            },
        ),
        migrations.CreateModel(
            name='FourthTaskHSK1Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk1.fourthtaskhsk1question')),
            ],
            options={
                'db_table': 'hsk1_listening_fourth_tasks_options',
            },
        ),
        migrations.AddField(
            model_name='fourthtaskhsk1',
            name='listening_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_type_tasks', to='hsk1.listeninghsk1'),
        ),
        migrations.AddField(
            model_name='firsttaskhsk1',
            name='listening_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_tasks', to='hsk1.listeninghsk1'),
        ),
        migrations.CreateModel(
            name='ReadingFirstTaskHSK1Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk1.readingfirsttaskhsk1')),
            ],
            options={
                'db_table': 'hsk1_reading_first_tasks_options',
            },
        ),
        migrations.CreateModel(
            name='ReadingFourthTaskHSK1Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk1.readingfourthtaskhsk1')),
            ],
            options={
                'db_table': 'hsk1_reading_fourth_tasks_options',
            },
        ),
        migrations.CreateModel(
            name='ReadingFourthTaskHSK1Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='hsk1.readingfourthtaskhsk1')),
            ],
            options={
                'db_table': 'hsk1_reading_fourth_tasks_sentences',
            },
        ),
        migrations.AddField(
            model_name='readingfourthtaskhsk1',
            name='reading_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_type_tasks', to='hsk1.readinghsk1'),
        ),
        migrations.AddField(
            model_name='readingfirsttaskhsk1',
            name='reading_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_tasks', to='hsk1.readinghsk1'),
        ),
        migrations.CreateModel(
            name='ReadingSecondTaskHSK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=255)),
                ('reading_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_type_tasks', to='hsk1.readinghsk1')),
            ],
            options={
                'db_table': 'hsk1_reading_second_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingSecondTaskHSK1Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='hsk1.readingsecondtaskhsk1')),
            ],
            options={
                'db_table': 'hsk1_reading_second_tasks_sentences',
            },
        ),
        migrations.CreateModel(
            name='ReadingThirdTaskHSK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_type_tasks', to='hsk1.readinghsk1')),
            ],
            options={
                'db_table': 'hsk1_reading_third_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingThirdTaskHSK1Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk1.readingthirdtaskhsk1')),
            ],
            options={
                'db_table': 'hsk1_reading_third_tasks_options',
            },
        ),
        migrations.CreateModel(
            name='ReadingThirdTaskHSK1Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='hsk1.readingthirdtaskhsk1')),
            ],
            options={
                'db_table': 'hsk1_reading_third_tasks_sentences',
            },
        ),
        migrations.CreateModel(
            name='SecondTaskHSK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=255)),
                ('listening_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_type_tasks', to='hsk1.listeninghsk1')),
            ],
            options={
                'db_table': 'hsk1_listening_second_tasks',
            },
        ),
        migrations.CreateModel(
            name='SecondTaskHSK1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk1.secondtaskhsk1')),
            ],
            options={
                'db_table': 'hsk1_listening_second_tasks_questions',
            },
        ),
        migrations.CreateModel(
            name='ThirdTaskHSK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=255)),
                ('listening_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_type_tasks', to='hsk1.listeninghsk1')),
            ],
            options={
                'db_table': 'hsk1_listening_third_tasks',
            },
        ),
        migrations.CreateModel(
            name='ThirdTaskHSK1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk1.thirdtaskhsk1')),
            ],
            options={
                'db_table': 'hsk1_listening_third_tasks_questions',
            },
        ),
    ]
