# Generated by Django 5.2.7 on 2025-10-16 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'listening_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'listening_tasks',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'reading_tasks',
            },
        ),
        migrations.CreateModel(
            name='FirstTaskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk3.firsttask')),
            ],
            options={
                'db_table': 'listening_first_task_questions',
            },
        ),
        migrations.AddField(
            model_name='firsttask',
            name='listening_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_tasks', to='hsk3.listening'),
        ),
        migrations.CreateModel(
            name='ReadingFirstTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_tasks', to='hsk3.reading')),
            ],
            options={
                'db_table': 'reading_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingFirstTaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk3.readingfirsttask')),
            ],
            options={
                'db_table': 'reading_first_task_options',
            },
        ),
        migrations.CreateModel(
            name='ReadingFirstTaskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk3.readingfirsttask')),
            ],
            options={
                'db_table': 'reading_first_task_questions',
            },
        ),
        migrations.CreateModel(
            name='ReadingSecondTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_tasks', to='hsk3.reading')),
            ],
            options={
                'db_table': 'reading_second_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingSecondTaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk3.readingsecondtask')),
            ],
            options={
                'db_table': 'reading_second_task_options',
            },
        ),
        migrations.CreateModel(
            name='ReadingSecondTaskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk3.readingsecondtask')),
            ],
            options={
                'db_table': 'reading_second_task_questions',
            },
        ),
        migrations.CreateModel(
            name='ReadingThirdTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('reading_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_tasks', to='hsk3.reading')),
            ],
            options={
                'db_table': 'reading_third_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingThirdTaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk3.readingthirdtask')),
            ],
            options={
                'db_table': 'reading_third_task_options',
            },
        ),
        migrations.CreateModel(
            name='SecondTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('listening_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_type_tasks', to='hsk3.listening')),
            ],
            options={
                'db_table': 'listening_second_tasks',
            },
        ),
        migrations.CreateModel(
            name='ThirdTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_type_tasks', to='hsk3.listening')),
            ],
            options={
                'db_table': 'listening_third_tasks',
            },
        ),
        migrations.CreateModel(
            name='ThirdTaskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk3.thirdtask')),
            ],
            options={
                'db_table': 'listening_third_task_questions',
            },
        ),
        migrations.CreateModel(
            name='ThirdTaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk3.thirdtaskquestion')),
            ],
            options={
                'db_table': 'listening_third_task_options',
            },
        ),
    ]
