# Generated by Django 5.2.7 on 2025-10-21 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsk3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'writing_tasks',
            },
        ),
        migrations.CreateModel(
            name='WritingFirstTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', models.TextField()),
                ('correct_answer', models.TextField()),
                ('writing_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_tasks', to='hsk3.writing')),
            ],
            options={
                'db_table': 'writing_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='WritingSecondTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('writing_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_tasks', to='hsk3.writing')),
            ],
            options={
                'db_table': 'writing_second_tasks',
            },
        ),
    ]
