# Generated by Django 5.2.7 on 2025-10-24 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTaskHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_letter', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'hsk5_listening_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='ListeningHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hsk5_listening_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingFirstTaskHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'hsk5_reading_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hsk5_reading_tasks',
            },
        ),
        migrations.CreateModel(
            name='WritingHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hsk5_writing_tasks',
            },
        ),
        migrations.CreateModel(
            name='FirstTaskHSK5Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk5.firsttaskhsk5')),
            ],
            options={
                'db_table': 'hsk5_listening_first_tasks_option',
            },
        ),
        migrations.AddField(
            model_name='firsttaskhsk5',
            name='listening_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_tasks', to='hsk5.listeninghsk5'),
        ),
        migrations.CreateModel(
            name='ReadingFirstTaskHSK5Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk5.readingfirsttaskhsk5')),
            ],
            options={
                'db_table': 'hsk5_reading_first_tasks_questions',
            },
        ),
        migrations.CreateModel(
            name='ReadingFirstTaskQuestionOptionHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk5.readingfirsttaskhsk5question')),
            ],
            options={
                'db_table': 'hsk5_reading_first_tasks_question_options',
            },
        ),
        migrations.AddField(
            model_name='readingfirsttaskhsk5',
            name='reading_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_tasks', to='hsk5.readinghsk5'),
        ),
        migrations.CreateModel(
            name='ReadingSecondTaskHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('reading_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_type_tasks', to='hsk5.readinghsk5')),
            ],
            options={
                'db_table': 'hsk5_reading_second_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingSecondTaskHSK5Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk5.readingsecondtaskhsk5')),
            ],
            options={
                'db_table': 'hsk5_reading_second_tasks_option',
            },
        ),
        migrations.CreateModel(
            name='ReadingThirdTaskHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('reading_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_type_tasks', to='hsk5.readinghsk5')),
            ],
            options={
                'db_table': 'hsk5_reading_third_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingThirdTaskHSK5Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk5.readingthirdtaskhsk5')),
            ],
            options={
                'db_table': 'hsk5_reading_third_tasks_questions',
            },
        ),
        migrations.CreateModel(
            name='ReadingThirdTaskQuestionOptionHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk5.readingthirdtaskhsk5question')),
            ],
            options={
                'db_table': 'hsk5_reading_third_task_question_options',
            },
        ),
        migrations.CreateModel(
            name='WritingFirstTaskHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_sentence', models.TextField()),
                ('words', models.TextField()),
                ('writing_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_tasks', to='hsk5.writinghsk5')),
            ],
            options={
                'db_table': 'hsk5_writing_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='WritingSecondTaskHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('writing_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_type_tasks', to='hsk5.writinghsk5')),
            ],
            options={
                'db_table': 'hsk5_writing_second_tasks',
            },
        ),
        migrations.CreateModel(
            name='WritingThirdTaskHSK5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=255)),
                ('writing_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_type_tasks', to='hsk5.writinghsk5')),
            ],
            options={
                'db_table': 'hsk5_writing_third_tasks',
            },
        ),
    ]
