# Generated by Django 5.2.7 on 2025-10-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTaskHSK2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hsk2_listening_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='ListeningHSK2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hsk2_listening_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingFirstTaskHSK2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hsk2_reading_first_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingFourthTaskHSK2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hsk2_reading_fourth_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingHSK2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hsk2_reading_tasks',
            },
        ),
        migrations.CreateModel(
            name='FirstTaskHSK2Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk2.firsttaskhsk2')),
            ],
            options={
                'db_table': 'hsk2_listening_first_tasks_questions',
            },
        ),
        migrations.AddField(
            model_name='firsttaskhsk2',
            name='listening_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_tasks', to='hsk2.listeninghsk2'),
        ),
        migrations.CreateModel(
            name='ReadingFirstTaskHSK2Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='hsk2.readingfirsttaskhsk2')),
            ],
            options={
                'db_table': 'hsk2_reading_first_tasks_sentences',
            },
        ),
        migrations.CreateModel(
            name='ReadingFourthTaskHSK2Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk2.readingfourthtaskhsk2')),
            ],
            options={
                'db_table': 'hsk2_reading_fourth_tasks_options',
            },
        ),
        migrations.CreateModel(
            name='ReadingFourthTaskHSK2Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk2.readingfourthtaskhsk2')),
            ],
            options={
                'db_table': 'hsk2_reading_fourth_tasks_questions',
            },
        ),
        migrations.AddField(
            model_name='readingfourthtaskhsk2',
            name='reading_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_type_tasks', to='hsk2.readinghsk2'),
        ),
        migrations.AddField(
            model_name='readingfirsttaskhsk2',
            name='reading_var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_type_tasks', to='hsk2.readinghsk2'),
        ),
        migrations.CreateModel(
            name='ReadingSecondTaskHSK2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_type_tasks', to='hsk2.readinghsk2')),
            ],
            options={
                'db_table': 'hsk2_reading_second_tasks',
            },
        ),
        migrations.CreateModel(
            name='ReadingSecondTaskHSK2Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk2.readingsecondtaskhsk2')),
            ],
            options={
                'db_table': 'hsk2_reading_second_tasks_options',
            },
        ),
        migrations.CreateModel(
            name='ReadingSecondTaskHSK2Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='hsk2.readingsecondtaskhsk2')),
            ],
            options={
                'db_table': 'hsk2_reading_second_tasks_sentences',
            },
        ),
        migrations.CreateModel(
            name='ReadingThirdTaskHSK2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sentence', models.TextField()),
                ('second_sentence', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('reading_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_type_tasks', to='hsk2.readinghsk2')),
            ],
            options={
                'db_table': 'hsk2_reading_third_tasks',
            },
        ),
        migrations.CreateModel(
            name='SecondTaskHSK2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.CharField(max_length=255)),
                ('listening_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_type_tasks', to='hsk2.listeninghsk2')),
            ],
            options={
                'db_table': 'hsk2_listening_second_tasks',
            },
        ),
        migrations.CreateModel(
            name='SecondTaskHSK2Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk2.secondtaskhsk2')),
            ],
            options={
                'db_table': 'hsk2_listening_second_tasks_questions',
            },
        ),
        migrations.CreateModel(
            name='ThirdTaskHSK2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_type_tasks', to='hsk2.listeninghsk2')),
            ],
            options={
                'db_table': 'hsk2_listening_third_tasks',
            },
        ),
        migrations.CreateModel(
            name='ThirdTaskHSK2Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_letter', models.CharField(max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hsk2.thirdtaskhsk2')),
            ],
            options={
                'db_table': 'hsk2_listening_third_tasks_questions',
            },
        ),
        migrations.CreateModel(
            name='ThirdTaskHSK2Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hsk2.thirdtaskhsk2question')),
            ],
            options={
                'db_table': 'hsk2_listening_third_tasks_options',
            },
        ),
    ]
